lib/src/country_selector.dart

if _filterByName and the user language not English will not Work, For that i added this

support input user search in translate language

---

example/lib/main.dart
example/pubspec.lock
lib/src/widgets/phone_form_field.dart
pubspec.lock
test/phone_form_field_test.dart

Fixes https://github.com/cedvdb/phone_form_field/issues/14
- added unit tests
- fixed some wrong unit tests
2 unit tests are still not passing, regarding onChanged and onSaved

Fix phone number type

---

CHANGELOG.md
lib/src/widgets/phone_form_field.dart
test/phone_form_field_test.dart

- fix onSaved & onChanged
- all unit test passing

Fix on changed and on saved

---

example/pubspec.lock
pubspec.yaml

- patch pubspec from 3.0.0 to 3.0.1

patch pubspec version

---

.github/workflows/ci.yml
pubspec.yaml

ci workflow

---

CHANGELOG.md
README.md
example/lib/main.dart
lib/src/widgets/phone_form_field.dart

expose autofill hints

---

README.md

**PR Type**
Documentation update
**Content**
Add Country selector section in main README file

docs(README): Add country selector section

---

lib/src/widgets/country_picker/country_selector.dart
test/_country_selector_test.dart

* fix unused noResultMessage property
* add related tests
* restore commented tests
Fix #50

fix(country-selector) : use noResultMessage properly

---

example/lib/main.dart
lib/src/widgets/phone_field_state.dart
test/phone_form_field_test.dart

well `widget.textDirection == TextDirection.rtl && widget.TextDirection == null` is always false.

fix a logical bug

---

example/lib/main.dart
lib/src/widgets/phone_field_state.dart
test/phone_form_field_test.dart

Reverts cedvdb/phone_form_field#110

Revert "fix a logical bug"

---

example/pubspec.lock
lib/src/widgets/country_selector/country_list.dart
lib/src/widgets/country_selector/country_selector.dart
lib/src/widgets/country_selector/country_selector_navigator.dart

Allow changing title and subtitle style on the dialog.

feat: add titleStyle and subTitle style

---

example/lib/main.dart
lib/src/widgets/country_selector/country_selector_navigator.dart

Hi, thank you very much for a super nice framework. It works perfectly in our project. Only a minor issue is that the Country Dialog takes almost the whole screen and it would be nice if we have an option to adapt this.

Add width and height parameters for DialogNavigator

---

example/pubspec.lock
lib/src/widgets/country_selector/country_list.dart
lib/src/widgets/country_selector/country_selector.dart
lib/src/widgets/country_selector/country_selector_navigator.dart
lib/src/widgets/country_selector/country_selector_page.dart
lib/src/widgets/country_selector/search_box.dart

Hello,
I have added some new customization properties to the `CountrySelectorNavigator` which are the following:
- For the `CountryList`, properties to customize the `titleStyle` & `subtitleStyle` for all the `CountrySelectorNavigator`s, not just the `BottomSheetNavigator`, and a property to customize the `scrollPhysics` of the list.
- For the `SearchBox`, properties to customize the `InputDecoration`, `TextStyle`, and Search Icon Color`.
I hope you like them.
Thanks ❤
Moaz El-sawaf

New customization properties to the `CountrySelectorNavigator`

---

lib/src/widgets/country_selector/country_list.dart
lib/src/widgets/country_selector/country_selector.dart
lib/src/widgets/country_selector/country_selector_navigator.dart
lib/src/widgets/country_selector/country_selector_page.dart

Add flag size, and use root navigator

Add flag size, and use root navigator

---

pubspec.yaml
test/_country_selector_navigator_test.dart
test/_country_selector_test.dart
test/phone_form_field_test.dart

circle_flags now use SVG for a smaller memory footprints.

Update to use latest version of circle_flags.

---

lib/src/widgets/country_selector/country_selector_navigator.dart

Supported safe area in bottom sheet of country selector

---

lib/src/widgets/country_selector/country_selector_navigator.dart
lib/src/widgets/country_selector/search_box.dart
lib/src/widgets/phone_field_state.dart
pubspec.yaml

The cursor color in the search box was always white, now it is set to provided text style color.
The Bottom Sheet default height was too small and the sheet was hidden behind keyboard.
Also downgrade intl version as it is not working in the current dev.

Fix search cursor color and initial bottom sheet height

---

example/lib/main.dart
lib/src/widgets/country_code_chip.dart
lib/src/widgets/phone_field.dart
lib/src/widgets/phone_field_state.dart
lib/src/widgets/phone_form_field.dart

This allows showing the selected country iso code, by default it is false.

FEAT: show selected country iso code feature implemented

---

lib/src/widgets/country_code_chip.dart
lib/src/widgets/phone_field.dart
lib/src/widgets/phone_field_state.dart
test/phone_form_field_test.dart

fix: disable country chip when field is disabled

---

CHANGELOG.md
README.md
lib/src/localization/generated/phone_field_localization_impl.dart
lib/src/localization/generated/phone_field_localization_impl_ko.dart
pubspec.yaml

Added Korean, Please merge this.

Add Korean

---

CHANGELOG.md
README.md
l10n/vi.arb
lib/src/localization/generated/phone_field_localization_impl.dart
lib/src/localization/generated/phone_field_localization_impl_vi.dart
pubspec.yaml

I added Vietnamese translation. Please merge this. Thanks

Add Vietnamese vi_VN translation

---

CHANGELOG.md
example/ios/Runner/AppDelegate.swift
example/lib/main.dart
lib/src/country_selector_navigator.dart
pubspec.yaml

- [✓] I have bumped the version in pubspec.yaml
- [✓] I have added an entry in changelog.md for the new pubspec version

added backgroundColor property to BottomSheet, DraggableModalSheet, ModalSheet, Dialog.

---

CHANGELOG.md
example/pubspec.lock
lib/src/country_button.dart
lib/src/country_button_style.dart
lib/src/phone_form_field_state.dart
pubspec.yaml

add: dropdownIconColor property to CountryButtonStyle

---

CHANGELOG.md
example/lib/main.dart
lib/src/country_button.dart
lib/src/country_button_style.dart
lib/src/phone_form_field_state.dart
pubspec.yaml

Added a border radius parameter to the country button

added border radius to button styles

---

CHANGELOG.md
pubspec.yaml

auto publish test #6

---

.github/workflows/publish.yml

reverted the workflow run

---

CHANGELOG.md
pubspec.yaml

auto publish test #8

---

.github/workflows/tag_creation.yml

Switched to personal access token for pushing ref

---

CHANGELOG.md
pubspec.yaml

auto publish test 9

---

.github/workflows/publish.yml
.github/workflows/tag_creation.yml

removed workflow dispatch

---

CHANGELOG.md
pubspec.yaml

auto publish test 11

---

CHANGELOG.md
pubspec.yaml

auto publish 12
